### ISSUE TITLE
Error: connection response is empty

### ISSUE THREAD

**Issue by alexs77** [iLert/terraform-provider-ilert#17] opened 2022-04-29 09:17 UTC
Often when I'm running `terraform apply`, it aborts with such an error:

```
╷
│ Error: connection response is empty
│ 
│   with module.warn_tls_cert_ttl_webtest["devops-shr-proc-testalert.azurewebsites.net"].ilert_connection.msteams["https://abc.webhook.office.com/webhookb2/…-9b8e4e6c6c3b@9ffa5805-cd82-46e7-8021-b83ff925f065/IncomingWebhook/0de243df23da43448f8114ff543aedd6/…-faacf7dafd2b"],
│   on modules/ilert_action/main.tf line 66, in resource "ilert_connection" "msteams":
│   66: resource "ilert_connection" "msteams" {
│ 
╵
```

It doesn't always fail with this error, though. It also doesn't always fail when trying to create a MS Teams connection; it sometimes also fails with email or webhook.

I now ran `terraform plan && terraform apply` a few times, and eventually it succeeded. With no changes to the Terraform source code or resources on ilert or Azure.

I'm happy to provide the Terraform source code and also a full debug log privately, as I do not want to reveal private information.

**Comment by STLVRTX** [comment] 2023-02-20 17:24
Could not reproduce the above error. With the implementation of the API v2 changes in Version 1.6.0 the above resource `ilert_connection` was deprecated, `ilert_alert_action` should be used now.
This error does not occur on new resource, closing.

**Closed by STLVRTX** 2023-02-20 17:24 UTC
