### ISSUE TITLE
ilert_alert_action - Jira issue type.

### ISSUE THREAD

**Issue by rauny-brandao** [iLert/terraform-provider-ilert#54] opened 2023-09-29 11:59 UTC
Hello there,

I'm using the ilert_alert_action resource to automate an Alert Action in Jira.

The issue lies with the expected issue_type. According to the [docs](https://registry.terraform.io/providers/iLert/ilert/latest/docs/resources/alert_action#jira-arguments), the `issue_type` parameter is optional and allows the following values: Bug, Epic, Subtask, Story, Task, with the default being Task.

However, my project doesn't have any of those predefined types. Instead, I'm using the following values: Service Request, Support, Incident, Change, Problem Report, and Problem Task. When I try to use any of these values, I encounter the following error:

```
Error: expected jira.0.issue_type to be one of [Bug, Epic, Subtask, Story, Task], but I received "Incident".
```

Using the iLert UI I can selected any issue type, example:
![CleanShot 2023-09-29 at 14 17 34@2x](https://github.com/iLert/terraform-provider-ilert/assets/13734862/a6c5bbb1-61b5-4859-9c1e-6b65382a6c46)

**Comment by STLVRTX** [comment] 2023-09-29 12:24
Hello, thank you for submitting the issue.
I just checked the corresponding code and indeed found an incorrect validation of this field.
The issue is already addressed in this [PR](https://github.com/iLert/terraform-provider-ilert/pull/55), and will be included in the next release.

**Closed** 2023-10-04 10:07 UTC
